### ISSUE TITLE
闇の石のかけら、こうかくレンズ、へんしんの翻訳の誤り

### ISSUE THREAD

**Issue by taizazanek** [thord-game/PixelmonReforged_ja_JP.lang#1]
・闇の石のかけら（item.pixelmon.dusk_stone_shard）が闇の石しのかけらになっている
・こうかくレンズの翻訳（item.pixelmon.wide_lens、item.pixelmon.wide_lens.tooltip）がものしりメガネとその説明文（item.pixelmon.wise_glasses、item.pixelmon.wise_glasses.tooltip）と同じものに誤訳されている
・技のへんしんの説明文（attack.transform.description）で、「変身」が「返信」となっている
修正お願いします。

**Comment by thord-game** [comment]
指摘大変ありがとうございます、修正しました！
