### ISSUE TITLE
改行コードの誤り

### ISSUE THREAD

**Issue by taizazanek** [thord-game/PixelmonReforged_ja_JP.lang#2]
Pixelmonの翻訳お疲れ様です。
カレー図鑑の各級の説明("gui.currydex.koffing.desc","ui.currydex.wobbuffet.desc","gui.currydex.milcery.desc","gui.currydex.copperajah.desc","gui.currydex.charizard.desc")と、レイドバトルの説明("raid.lorespecial")の改行のコードが『\\n』から『\n』になっており、正しく改行されていませんでした。修正お願いします。
また、カレー図鑑の各級の説明の句点が『。』ではなく『.』になってるのと、Pixelmonのen_us.jsonファイルでは"raid.lore"に改行が使われているのに対し、PixelmonReforged_ja_JP.langの"raid.lore"には改行が使われていないのは誤りでしょうか？誤りでしたら修正お願いします。

**Comment by thord-game** [comment]
指摘ありがとうございます、修正しました。
