### ISSUE TITLE
スペースが半角から全角になっている間違い

### ISSUE THREAD

**Issue by taizazanek** [thord-game/PixelmonReforged_ja_JP.lang#3]
サーナイトナイトの説明(item.pixelmon.gardevoirite.tooltip)、ほんきをだす こうげき(attack.pulverizing_pancake)、オリジンズスーパーノヴァの説明(attack.genesis_supernova.description)、ココガラの図鑑説明(pixelmon.rookidee.description)、マスターランクリボンの説明(ribbon.master_rank.description)のスペースが半角から全角になっている部分があり、表示がおかしくなっています。
修正お願いします。

**Comment by thord-game** [comment]
いつも指摘ありがとうございます。修正しました。
