### ISSUE TITLE
たいりょくのハネの説明

### ISSUE THREAD

**Issue by taizazanek** [thord-game/PixelmonReforged_ja_JP.lang#4]
たいりょくのハネの説明(item.pixelmon.health_feather.tooltip)のマックスアップと書かれるべきところが「HP UP」と未翻訳になっています。
また、ポイントアップ(item.pixelmon.pp_up)とポイントマックス(item.pixelmon.pp_max)がまだ未翻訳になっています。

**Comment by thord-game** [comment]
いつも指摘ありがとうございます、修正しました。
