### ISSUE TITLE
ルアーとルアーの説明文の翻訳

### ISSUE THREAD

**Issue by taizazanek** [thord-game/PixelmonReforged_ja_JP.lang#5]
ルアーの説明文の翻訳が少し不自然だと思います。
lure.strong.normal.tooltipの翻訳を「%sタイプのポケモンのスポーン率を3倍にする」、lure.weak.normal.tooltipの翻訳を「%sタイプのポケモンのスポーン率を1.5倍にする」、
lure.strong.special.tooltipの翻訳を「%sのポケモンのスポーン率を1.73倍にする」、
lure.weak.special.tooltipの翻訳を「%sのポケモンのスポーン率を1.22倍にする」とすれば不自然じゃないと思いますがいかがでしょうか。
また、item.pixelmon.lure_shiny_weakの翻訳を「よわい光るルアー」、item.pixelmon.lure_shiny_strongの翻訳を「つよい光るルアー」と翻訳していますが、それぞれ「よわい色違いのルアー」、「つよい色違いのルアー」と訳した方が適切だと思います。

**Comment by thord-game** [comment]
指摘頂いた通り、修正しました。
