### ISSUE TITLE
レコードとルアーの翻訳

### ISSUE THREAD

**Issue by taizazanek** [thord-game/PixelmonReforged_ja_JP.lang#6]
言語ファイルの更新お疲れ様です。

この言語ファイルではMusic Discを「音楽ディスク」と翻訳されていますが、バニラではMusic Discを「レコード」と翻訳されているので、それに合わせてレコードと翻訳した方がいいと思います。

タイプに関するルアーの翻訳が「○○のルアー」と「○○ルアー」と表記が二種類あるので、どちらかに統一した方がいいと思います。

修正お願い致します。

**Comment by thord-game** [comment]
指摘ありがとうございます。
音楽ディスクはレコードに直し、ルアーは前回とあわせて「のルアー」に統一しました。
